= Advanced AsciiDoc features
Author Name <author@email.org>
v2.0, 2019-03-22
:toc:
:fonts: icon
:myattribute: myvalue
:toc:
:toclevels: 4
:source-highlighter: highlight.js
:icons: font

This is the preamble Text. 

== Links

Simple Weblinks can be written like https://asciidoctor.org[Asciidoctor].

You can link to other documents link:../document.adoc[template document].

== Source code block

[source,ruby,linenums]
----
require 'sinatra'   <1>

get '/hi' do        <2>
  "Hello World!"
end
----
<1> Explain a line
<2> Explain another line


== Automatic TOC

Add `:toc:` to the header. 

=== Basic Table

.Table Title
|===
|Item |Description

|A star | Bright and shiny
|A planet | Round and blue
|Galaxy
|Large and beautful
|===

* Emtpy line = header

=== Advanced Tables

[%header,cols=">1,^2h,6"]
|===
|ID| tables | with explanations
|1| structured presentation | often important for specifications
|2| Features | like weight, alignment, ...
|3 2.2+^.^| or connected cells
|4 
|5| My | Style of writing
|===


=== Comments

// A single-line comment

////
A multi-line comment.

Notice it's a delimited block.
////


=== Icons

Render more beautiful documents by adding `:icons: font` in header

Now you can use icon:image[]. 

Look up icons via https://fontawesome.com/search 

*Important:* check 5.15.4 in the search filter! And even then, not all are working




== Admonitions


NOTE: An admonition draws the reader's attention to auxiliary information.

[IMPORTANT]
Don't forget the children!

TIP: Look for the warp zone under the bridge.

CAUTION: Slippery when wet.

WARNING: The software you're about to use is untested.

IMPORTANT: Sign off before stepping away from your computer.


== More Blocks

.A sidebar
****
Sidebar
****

.Quote
[quote,Abraham Lincoln,Cemetery at Gettysburg]
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...
____


.Plain block

This is very helpful to apply styling in reveal js!

[.mycssclass]
--
An open block can be an anonymous container,
or it can masquerade as any other block.
--


== Including files

//include::workshop-interactive-demosession1.adoc[leveloffset=+2]


You can also include text files, i.e. into blocks

[source,java]
--
include::FibCalculator.java[]
--



